# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-10-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMBD_app', '0003_temp_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('encrypted_image', models.TextField()),
            ],
        ),
    ]
